{
 "title": "dev_nch293",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "component", "query": { "query": "queue" } },
   { "name": "up", "query": { "query": "up" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Self Hadoop Monitoring\n\n## 현재 dev Cluster 의 Dashboard 화면입니다.\n\n## 주의 사항\n- 너무 잦은 Refresh는 지양해 주세요.\n\n## Links\n- Self Hadoop "
   }
  },
  { "title": "Cluster Component Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Component Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "component_ambari_metrics_check", "legendFormat": "Ambari" },
    { "expr": "component_hbase_check", "legendFormat": "HBase" },
    { "expr": "component_hdfs_check", "legendFormat": "hdfs" },
    { "expr": "component_yarn_check", "legendFormat": "yarn" },
    { "expr": "component_zookeeper_check", "legendFormat": "zookeeper" },
    { "expr": "component_mapreduce_2_check", "legendFormat": "mapreduce" }
   ]
  },
  {
   "title": "NodeManager",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "datanode1_process_nodemanager_check",
     "legendFormat": "datanode1"
    },
    {
     "expr": "datanode2_process_nodemanager_check",
     "legendFormat": "datanode2"
    },
    {
     "expr": "datanode3_process_nodemanager_check",
     "legendFormat": "datanode3"
    },
    {
     "expr": "datanode4_process_nodemanager_check",
     "legendFormat": "datanode4"
    },
    {
     "expr": "datanode5_process_nodemanager_check",
     "legendFormat": "datanode5"
    },
    {
     "expr": "datanode6_process_nodemanager_check",
     "legendFormat": "datanode6"
    }
   ]
  },
  {
   "title": "Resource Manager",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rm_active", "legendFormat": "active" },
    { "expr": "rm_standby", "legendFormat": "standby" }
   ]
  },
  {
   "title": "DataNode",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "yarn_active_nodes", "legendFormat": "total" },
    {
     "expr": "datanode1_process_datanode_check",
     "legendFormat": "datanode1"
    },
    {
     "expr": "datanode2_process_datanode_check",
     "legendFormat": "datanode2"
    },
    {
     "expr": "datanode3_process_datanode_check",
     "legendFormat": "datanode3"
    },
    {
     "expr": "datanode4_process_datanode_check",
     "legendFormat": "datanode4"
    },
    {
     "expr": "datanode5_process_datanode_check",
     "legendFormat": "datanode5"
    },
    {
     "expr": "datanode6_process_datanode_check",
     "legendFormat": "datanode6"
    }
   ]
  },
  { "title": "Yarn Application Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Application Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "yarn_apps_submitted", "legendFormat": "submitted" },
    { "expr": "yarn_apps_running", "legendFormat": "running" },
    { "expr": "yarn_apps_completed", "legendFormat": "completed" },
    { "expr": "yarn_apps_failed", "legendFormat": "failed" },
    { "expr": "yarn_apps_killed", "legendFormat": "killed" },
    { "expr": "yarn_apps_pending", "legendFormat": "pending" }
   ]
  },
  {
   "title": "Running Apps",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "yarn_apps_running", "legendFormat": "running" },
    { "expr": "yarn_apps_pending", "legendFormat": "pending" }
   ]
  },
  {
   "title": "Finished Apps",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "yarn_apps_failed", "legendFormat": "failed" },
    { "expr": "yarn_apps_completed", "legendFormat": "completed" },
    { "expr": "yarn_apps_killed", "legendFormat": "killed" }
   ]
  },
  {
   "title": "Yarn Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "yarn_allocated_mb", "legendFormat": "yarn_allocated_mb" },
    { "expr": "yarn_available_mb", "legendFormat": "yarn_available_mb" },
    { "expr": "yarn_reserved_mb", "legendFormat": "yarn_reserved_mb" },
    { "expr": "yarn_total_mb", "legendFormat": "yarn_total_mb" }
   ]
  },
  {
   "title": "Yarn CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "yarn_allocated_virtual_cores", "legendFormat": "allocated_virtual_cores" },
    { "expr": "yarn_available_virtual_cores", "legendFormat": "available_virtual_cores" },
    { "expr": "yarn_reserved_virtual_cores", "legendFormat": "reserved_virtual_cores" },
    { "expr": "yarn_total_virtual_cores", "legendFormat": "total_virtual_cores" }
   ]
  },
  {
   "title": "Yarn Containers",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "yarn_containers_allocated", "legendFormat": "allocated" },
    { "expr": "yarn_containers_pending", "legendFormat": "pending" },
    { "expr": "yarn_containers_reserved", "legendFormat": "reserved" }
   ]
  },
  { "title": "Name Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Memory Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dev_nch292_ncl_mem_heap_committed_m"
    },
    { "expr": "dev_nch292_ncl_mem_heap_max_m" },
    { "expr": "dev_nch292_ncl_mem_heap_used_m" }
   ]
  },
  {
   "title": "Memory Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dev_nch293_ncl_mem_heap_committed_m"
    },
    { "expr": "dev_nch293_ncl_mem_heap_max_m" },
    { "expr": "dev_nch293_ncl_mem_heap_used_m" }
   ]
  },
  {
   "title": "Memory Non Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dev_nch292_ncl_mem_non_heap_committed_m"
    },
    {
     "expr": "dev_nch292_ncl_mem_non_heap_max_m"
    },
    {
     "expr": "dev_nch292_ncl_mem_non_heap_used_m"
    }
   ]
  },
  {
   "title": "Memory Non Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dev_nch293_ncl_mem_non_heap_committed_m"
    },
    {
     "expr": "dev_nch293_ncl_mem_non_heap_max_m"
    },
    {
     "expr": "dev_nch293_ncl_mem_non_heap_used_m"
    }
   ]
  },
  { "title": "Data Note Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "DFS Usage Percent",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "datanode1_dfs_usage_percent", "legendFormat": "datanode1" },
    { "expr": "datanode2_dfs_usage_percent", "legendFormat": "datanode2" },
    { "expr": "datanode3_dfs_usage_percent", "legendFormat": "datanode3" },
    { "expr": "datanode4_dfs_usage_percent", "legendFormat": "datanode4" },
    { "expr": "datanode5_dfs_usage_percent", "legendFormat": "datanode5" },
    { "expr": "datanode6_dfs_usage_percent", "legendFormat": "datanode6" }
   ]
  },
  {
   "title": "DFS Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "datanode1_dfs_usage/1024/1024", "legendFormat": "datanode1" },
    { "expr": "datanode2_dfs_usage/1024/1024", "legendFormat": "datanode2" },
    { "expr": "datanode3_dfs_usage/1024/1024", "legendFormat": "datanode3" },
    { "expr": "datanode4_dfs_usage/1024/1024", "legendFormat": "datanode4" },
    { "expr": "datanode5_dfs_usage/1024/1024", "legendFormat": "datanode5" },
    { "expr": "datanode6_dfs_usage/1024/1024", "legendFormat": "datanode6" }
   ]
  },
  { "title": "Queue Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Queue Stats",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "queue_default_num_applications", "legendFormat": "total_apps" },
    {
     "expr": "queue_default_num_active_applications",
     "legendFormat": "active_apps"
    },
    {
     "expr": "queue_default_num_pending_applications",
     "legendFormat": "pending_apps"
    },
    { "expr": "queue_default_num_containers", "legendFormat": "containers" },
    {
     "expr": "queue_default_pending_containers",
     "legendFormat": "pending_containers"
    },
    {
     "expr": "queue_default_reserved_containers",
     "legendFormat": "reserved_containers"
    }
   ]
  },
  {
   "title": "namespace usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namespace_metric_capacity_total/1024/1024/1024",
     "legendFormat": "capacity_total (GB)"
    },
    {
     "expr": "namespace_metric_capacity_used/1024/1024/1024",
     "legendFormat": "capacity_used (GB)"
    },
    {
     "expr": "namespace_metric_capacity_remaining/1024/1024/1024",
     "legendFormat": "capacity_remaining (GB)"
    }
   ]
  },
  {
   "title": "datanode usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namespace_metric_datanode_usage_max",
     "legendFormat": "datanode_usage_max"
    },
    {
     "expr": "namespace_metric_datanode_usage_median",
     "legendFormat": "datanode_usage_median"
    },
    {
     "expr": "namespace_metric_datanode_usage_min",
     "legendFormat": "datanode_usage_min"
    }
   ]
  },
  {
   "title": "node stats",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 91 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namespace_metric_live_nodes_count",
     "legendFormat": "live_nodes"
    },
    {
     "expr": "namespace_metric_dead_nodes_count",
     "legendFormat": "dead_nodes"
    },
    {
     "expr": "namespace_metric_decommission_nodes_count",
     "legendFormat": "decommission_nodes"
    },
    {
     "expr": "namespace_metric_maintenance_nodes_count",
     "legendFormat": "maintenance_nodes"
    },
    {
     "expr": "namespace_metric_nodes_in_service",
     "legendFormat": "nodes_in_service"
    }
   ]
  }
 ]
}